# Generated by Django 2.0.5 on 2018-08-12 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_month_hayagaeri', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='person_id',
        ),
    ]
