# Generated by Django 2.0.5 on 2018-08-13 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_month_hayagaeri', '0002_remove_person_person_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hayagaeri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=50, verbose_name='予定')),
                ('result', models.CharField(max_length=50, verbose_name='結果')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='hayagaeri',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_month_hayagaeri.Hayagaeri'),
            preserve_default=False,
        ),
    ]
