# Generated by Django 2.0.5 on 2018-08-13 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_month_hayagaeri', '0004_auto_20180813_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='HayagaeriPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('', 'NoPlanDay'), ('○', 'PlanDay'), ('早週', 'HayagaeriWeek')], max_length=50, verbose_name='予定')),
            ],
        ),
        migrations.AlterField(
            model_name='schedule',
            name='hayagaeri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_month_hayagaeri.HayagaeriPlan'),
        ),
        migrations.DeleteModel(
            name='Hayagaeri',
        ),
    ]
