# Generated by Django 2.0.5 on 2018-08-13 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_month_hayagaeri', '0009_auto_20180813_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='HayagaeriPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=50, verbose_name='早帰り予定')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='hayagaeri_plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_month_hayagaeri.HayagaeriPlan'),
            preserve_default=False,
        ),
    ]
