# Generated by Django 2.0.5 on 2018-08-13 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_month_hayagaeri', '0010_auto_20180813_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='HayagaeriResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=50, verbose_name='早帰り実績')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='hayagaeri_result',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_month_hayagaeri.HayagaeriResult'),
            preserve_default=False,
        ),
    ]
