# Generated by Django 2.0.5 on 2018-08-13 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_month_hayagaeri', '0011_auto_20180813_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='description',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='summary',
        ),
    ]
