# Generated by Django 2.0.5 on 2018-08-13 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_month_hayagaeri', '0012_auto_20180813_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='description',
            field=models.TextField(blank=True, verbose_name='詳細な説明'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(default=datetime.time(7, 0), verbose_name='終了時間'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(default=datetime.time(7, 0), verbose_name='開始時間'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='summary',
            field=models.CharField(default=1, max_length=50, verbose_name='概要'),
            preserve_default=False,
        ),
    ]
