# Generated by Django 2.0.5 on 2018-08-13 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_month_hayagaeri', '0014_remove_schedule_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='description',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='end_time',
        ),
    ]
